### PR TITLE
Add NovelPub Filter

### PR DESCRIPTION
**Pull request by raw-chicken**
Added simple regex filter for NovelPub.

NovelPub / LightNovelWorld / LightNovelPub include messages in this format:
`<strong><strong>message here</strong></strong>`

Added simple filter in NovelPub's blacklist and a new conditional in the crawler that checks each entire element for the structure
`<p><strong><strong>message</strong></strong></p`
to filter out the messages.

### CODE REVIEW

**Comment by mensch272** [comment]
Would you please provide an example of this on either website?

**Comment by raw-chicken** [comment]
For example on [novelpub](https://www.novelpub.com/novel/born-to-be-rebellious-quick-transmigration/1360-chapter-1), the following text is in chapter-content where the rest of the text is:
ex1

It is displayed as:
ex2

I believe that the normal filter would not work as they have variations on the actual content of the message which is what the filter searches in. However, they all have the same tags surround them which do not normally appear in any novels (because such tags are redundant) as seen below, and can be thus filtered out:
image

**Comment by raw-chicken** [comment]
New output (first 3 chapters in html format)
[cleaned.zip](https://github.com/mensch272/novelsave_sources/files/8695247/cleaned.zip)

Compared to the current output of NovelSave bot (in epub format):
[btbr.zip](https://github.com/mensch272/novelsave_sources/files/8695249/btbr.zip)

Original: 
image

Cleaned:
image

**Comment by mensch272** [comment]
I understand the problem now. However, using regex to select html is a bad method.

See:

- https://stackoverflow.com/questions/590747/using-regular-expressions-to-parse-html-why-not
- https://www.google.com/url?sa=t&source=web&rct=j&url=https://spin.atomicobject.com/2018/02/21/regular-expressions/&ved=2ahUKEwj6vKzQ5OH3AhUz63MBHfXZAWQQFnoECA8QAQ&usg=AOvVaw0WUZVEccP2Jnq8fq5ShADh

A better way to implement this would be to select all `strong > strong` with query selector and remove them using `extract` method from bs4.

```
for strong in content.select_all('strong > strong'):
    strong.extract()

# removes the now empty elements
self.clean_contents(content)
```

**Comment by raw-chicken** [comment]
Interesting, I wasn't aware. I removed the previous changes and added
```
for strong in content.select('strong > strong'):
  strong.extract()
```
and quickly tested it, and it works now.

**Comment by mensch272** [comment]
@raw-chicken Could you please resolve the comments so that I may merge the pr?

**Comment by mensch272** [comment]
Thank you.

**Pull request merged**
